In [1]:
# adding 2 to a python list
py_list=[1,3,5,7,9] 
py_list_with_2=[x+2 for x in py_list]
print("python list with 2 added :",py_list_with_2)

# adding 2 to a Numpy list
import numpy as np

numpy_array=np.array([1,3,5,7,9])
numpy_array_with_2=numpy_array+2
print("numpy list with 2 added :",numpy_array_with_2)


python list with 2 added : [3, 5, 7, 9, 11]


numpy list with 2 added : [ 3  5  7  9 11]


In [2]:
import time
#create large array
py_list=list(range(10**6))
numpy_array=np.array(range(10**6))

#measure the time taken for element-wise addition
start_time = time.time()
py_list_sum=[x+2 for x in py_list]
end_time=time.time()
print(f"time taken for python list :{end_time-start_time}seconds")

start_time=time.time()
numpy_array_sum=numpy_array+2
end_time=time.time()
print(f"taken time for numpy :{end_time-start_time}seconds")


time taken for python list :0.08116292953491211seconds
taken time for numpy :0.002105236053466797seconds


In [3]:
import numpy as np
arr1=np.arange(0,10,3)
arr1

array([0, 3, 6, 9])

In [4]:
arr2=np.linspace(0,10,num=4,endpoint=True)
arr2

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [5]:
a=np.linspace(0,20,10,endpoint=False,dtype='int')
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr3=np.array([5,8,10])
arr3

array([ 5,  8, 10])

In [7]:
arr3.shape

(3,)

In [8]:
arr4=np.arange(5,14,2)
print(arr4)

[ 5  7  9 11 13]


In [9]:
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr5.shape

(3, 3)

In [11]:
arr6=np.arr

AttributeError: module 'numpy' has no attribute 'arr'

In [104]:
arr6=np.zeros((3,4),dtype=float)
arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [105]:
arr6=np.ones((3,4),dtype=str)
arr6

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [106]:
arr8=np.empty((3,4),dtype='int')
arr8

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [107]:
nested_list=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
nested_list

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [108]:
shape=(2,3,4)
arr11=np.zeros(shape,dtype='int')
arr11

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [109]:
shape=(2,3,4)
arr11=np.ones(shape,dtype='int')
arr11

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [110]:
shape=(2,3,4)
arr11=np.empty(shape,dtype='int')
arr11

array([[[      2265876526264,                 156,                   0,
                           0],
        [       197568495616, 4189017755886035579, 3419490394216495904,
         2322206415472651376],
        [6568633515958755618, 3328195498517344347, 2318263290953739317,
         2336906602263948849]],

       [[3628529247127085088, 3185503104257499182, 3329039923447477024,
         2314885866833337653],
        [2318848424128028704, 3828108290184978476, 6716325225000869934,
         7863883274792347997],
        [2477389231675241573, 7287422522494754874, 7957695015493526904,
         4189038621173441375]]])

In [111]:
random_no=np.random.randn(2,3)
random_no

array([[-0.46099289,  0.07576436, -0.33595634],
       [ 0.61401966, -1.1170012 , -0.73921543]])

In [112]:
random_no=np.random.randint(-10,10,size=(2,3))
random_no

array([[-8,  4,  9],
       [-4, -9,  3]], dtype=int32)

In [113]:
b=np.array([2,4,6,8,10])
b

array([ 2,  4,  6,  8, 10])

In [114]:
type(b)

numpy.ndarray

In [115]:
i=np.identity(2)
i

array([[1., 0.],
       [0., 1.]])

In [116]:
diagonal_matrix=np.diag([1,2,3])
diagonal_matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [117]:
x=np.array([1,2,3])
y=x
z=np.copy(x)
print(x,y,z)

[1 2 3] [1 2 3] [1 2 3]


In [118]:
c=np.array([11,22,33],dtype='int')
c

array([11, 22, 33])

In [119]:
import numpy as np
so=np.arange(12).reshape(3,4)
so

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
so+4

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
so-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [122]:
so*2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [123]:
so/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [124]:
so%2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [125]:
ro=np.arange(12).reshape(3,4)
ro

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
ro>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [127]:
ro<5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [128]:
ro==5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [129]:
ro!=5

array([[ True,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [130]:
ro<=5


array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [131]:
ro>=5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [132]:
lo=np.array([1,5,9])
lo1=np.array([2,4,7])
comp =lo>lo1
comp

array([False,  True,  True])

In [133]:
lo2=np.array([True,False,True,False])
lo3=np.array([False,True,False,False])
_and = np.logical_and(lo2,lo3)
print(_and)
_or = np.logical_or(lo2,lo3)
print(_or)

[False False False False]
[ True  True  True False]


In [134]:
arr1=np.array([1,3,7])
arr2=np.array([2,3,6])
result_and = np.logical_and(arr1>2 , arr2>2)
print(result_and)
result_or = np.logical_or(arr1>2, arr2>2)
result_or

[False  True  True]


array([False,  True,  True])

In [135]:
vo=np.array([1,2,3])+4
vo1=np.array([4,5,6])
addition=vo+vo1
subtration=vo-vo1
multiplation=vo*vo1
division=vo/vo1
print(vo)
print(addition,subtration,multiplation,division)

[5 6 7]
[ 9 11 13] [1 1 1] [20 30 42] [1.25       1.2        1.16666667]


In [136]:
za=np.arange(12).reshape(3,4)
zb=np.arange(12,24).reshape(3,4)
za,zb

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [137]:
addition=za+zb
subtration=za-zb
multiplation=za*zb
division=za/zb

In [138]:
ao=np.random.random((3,4))
ao

array([[0.95792938, 0.99174981, 0.26044947, 0.55493953],
       [0.6517811 , 0.77718187, 0.45720067, 0.50110859],
       [0.94550267, 0.97990283, 0.14571661, 0.34677476]])

In [139]:
ao=np.round(ao*100)
ao

array([[96., 99., 26., 55.],
       [65., 78., 46., 50.],
       [95., 98., 15., 35.]])

In [142]:
aa1=np.sum(ao,axis=1)
aa1

array([276., 239., 243.])

In [145]:
a1 =np.max(ao)
a11=np.max(ao, axis=1)
a22=np.min(ao,axis=0)
a2=np.min(ao)
a3=np.prod(ao)
a1,a11,a22,a3


(np.float64(99.0),
 array([99., 78., 98.]),
 array([65., 78., 15., 35.]),
 np.float64(7.7461739403048e+20))

In [146]:
st=np.random.random((3,3))
st

array([[0.87297493, 0.59613267, 0.49939885],
       [0.26237663, 0.95845247, 0.70290761],
       [0.66061025, 0.87491219, 0.08123447]])

In [148]:
avg=np.sum(st)/np.size(st)
np.round(avg,2)

np.float64(0.61)

In [150]:
b1=np.mean(st)
b11=st.mean(axis=0)
b2=np.median(st)
b22=np.median(st,axis=1)
b3=np.var(st)
b4=np.std(st)
b1,b11,b2,b22,b3,b4

(np.float64(0.6121111184713116),
 array([0.59865394, 0.80983244, 0.42784698]),
 np.float64(0.6606102486700348),
 array([0.59613267, 0.70290761, 0.66061025]),
 np.float64(0.07608515906346273),
 np.float64(0.2758353839946259))

In [152]:
tf=np.arange(12,24).reshape(3,4)
tf1=np.arange(36,48).reshape(3,4)
tf

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [153]:
np.sin(tf)

array([[-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 ]])

In [155]:
np.cos(tf)

array([[ 0.84385396,  0.90744678,  0.13673722, -0.75968791],
       [-0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302]])

In [156]:
np.tan(tf)

array([[-0.63585993,  0.46302113,  7.24460662, -0.8559934 ],
       [ 0.30063224,  3.49391565, -1.13731371,  0.15158947],
       [ 2.23716094, -1.52749853,  0.00885166,  1.58815308]])

In [157]:
np.log(100)


np.float64(4.605170185988092)

In [158]:
np.exp(10)

np.float64(22026.465794806718)

In [159]:
np.sqrt(25)

np.float64(5.0)

In [160]:
np.power(2,3)

np.int64(8)

In [162]:
arr4=np.array([10,20,30,40,50])
sqrt_result=np.sqrt(arr4)
print(sqrt_result)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [163]:
arr=np.array([1.23,2.78,3.59,4.55])
rounded_arr=np.round(arr,2)
print(rounded_arr)

[1.23 2.78 3.59 4.55]


In [164]:
arr=np.array([1.2,2.5,3.9,4.2])
floored_arr=np.floor(arr)
print(floored_arr)

[1. 2. 3. 4.]


In [165]:
np.floor(np.random.random((2,3))*100)

array([[33., 90., 26.],
       [62., 68., 45.]])

In [168]:
arr=np.array([1.2,2.7,3.5,4.9])
ceiled_arr=np.ceil(arr)
print(ceiled_arr)

[2. 3. 4. 5.]


In [169]:
np.ceil(np.random.random((2,3))*100)

array([[26., 61., 62.],
       [32., 49., 53.]])

In [172]:
m=np.array([1,2,3,4,5,6])
n=np.array([3,4,5,6,7,8])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [173]:
np.intersect1d(m,n)

array([3, 4, 5, 6])

In [174]:
import numpy as np
idx =np.array([10,20,30,40,50])
first_element=idx[0]
sub_array=idx[1:4]
a=idx[-1]
first_element,sub_array,a

(np.int64(10), array([20, 30, 40]), np.int64(50))

In [175]:
p1=np.arange(10)
p2=np.arange(12).reshape(3,4)
p3=np.arange(8).reshape(2,2,2)


In [176]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [177]:
p2[:,2]

array([ 2,  6, 10])

In [178]:
p2[:3:2,:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [179]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [180]:
print(p3[1,0,1])
p3[0,1,0]

5


np.int64(2)

In [184]:
print(p3[1,1,1])

7


In [185]:
p2[0:1]

array([[0, 1, 2, 3]])

In [187]:
p1[2:5:2]

array([2, 4])

In [189]:
p2[0,:]

array([0, 1, 2, 3])

In [190]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [191]:
p3[0,1,:]

array([2, 3])

In [193]:
p3[1,:,1]

array([5, 7])

In [1]:
import numpy as np
i=np.array([10,20,30,110])
items=[10,20,30,40,50,60,70,80,90,110]
np.isin(i,items)

array([ True,  True,  True,  True])

In [2]:
i[np.isin(i,items)]

array([ 10,  20,  30, 110])

In [4]:
np.isin(30,items)

array(True)

In [8]:
arr=np.array([[1,3,5],[8,2,4]]).reshape(3,2)
print(arr)
max_index=np.argmax(arr)
print("index of max value:",max_index)
maxx_indices_col=np.argmax(arr,axis=1)
print("index of max in coloum:",maxx_indices_col)

[[1 3]
 [5 8]
 [2 4]]
index of max value: 3
index of max in coloum: [1 1 1]


In [10]:
arr=np.array([[1,3,5],[8,2,4]]).reshape(3,2)
print(arr)
min_index=np.argmin(arr)
print("index of min value:",min_index)
minn_indices_col=np.argmin(arr,axis=0)
print("index of min in coloum:",minn_indices_col)

[[1 3]
 [5 8]
 [2 4]]
index of min value: 0
index of min in coloum: [0 0]


In [12]:
wh=np.arange(12)
print(wh)
np.where(wh>5)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(array([ 6,  7,  8,  9, 10, 11]),)

In [13]:
np.where(wh>5,1,wh)

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1, 1, 1])

In [15]:
p1=np.arange(10)
for i in p1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [18]:
p2=np.arange(12).reshape(3,4)
for i in p2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [20]:
p2=np.arange(12).reshape(3,4)
for i in p2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [21]:
for i in np.nditer(p2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [22]:
p3=np.arange(8).reshape(2,2,2)
for i in p3:
    for j in i:
        print(j)

[0 1]
[2 3]
[4 5]
[6 7]


In [25]:
for i in np.nditer(p3):
    print(i)

0
1
2
3
4
5
6
7


In [26]:
p4=np.arange(12,24).reshape(3,4)
p4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
for i in np.nditer(p4):
    print(i)

12
13
14
15
16
17
18
19
20
21
22
23


In [31]:
s=np.random.randint(1,100,15)
s1=np.random.randint(1,100,24).reshape(6,4)
s,s1

(array([36, 39, 33, 34, 79,  2, 53, 56, 88, 22, 73, 64, 24, 83, 43],
       dtype=int32),
 array([[ 2, 18, 97, 32],
        [36, 57, 79, 30],
        [27, 24, 83, 43],
        [23, 32, 41, 26],
        [24, 86,  5, 61],
        [ 7, 29, 50, 86]], dtype=int32))

In [32]:
g=np.sort(s)
s

array([36, 39, 33, 34, 79,  2, 53, 56, 88, 22, 73, 64, 24, 83, 43],
      dtype=int32)

In [33]:
np.sort(s)[::-1]

array([88, 83, 79, 73, 64, 56, 53, 43, 39, 36, 34, 33, 24, 22,  2],
      dtype=int32)

In [34]:
np.sort(s1)

array([[ 2, 18, 32, 97],
       [30, 36, 57, 79],
       [24, 27, 43, 83],
       [23, 26, 32, 41],
       [ 5, 24, 61, 86],
       [ 7, 29, 50, 86]], dtype=int32)

In [36]:
np.sort(s1,axis=0)

array([[ 2, 18,  5, 26],
       [ 7, 24, 41, 30],
       [23, 29, 50, 32],
       [24, 32, 79, 43],
       [27, 57, 83, 61],
       [36, 86, 97, 86]], dtype=int32)

In [37]:
np.append(s1,2)

array([ 2, 18, 97, 32, 36, 57, 79, 30, 27, 24, 83, 43, 23, 32, 41, 26, 24,
       86,  5, 61,  7, 29, 50, 86,  2])

In [38]:
np.shape(s1)

(6, 4)

In [39]:
np.append(s1,np.ones((6,1)).astype('int'))

array([ 2, 18, 97, 32, 36, 57, 79, 30, 27, 24, 83, 43, 23, 32, 41, 26, 24,
       86,  5, 61,  7, 29, 50, 86,  1,  1,  1,  1,  1,  1])

In [41]:
e=np.array([1,1,1,1,1,2,2,2,3,3,3,5,6,7,9,9])
np.unique(e)

array([1, 2, 3, 5, 6, 7, 9])

In [42]:
dp=np.array([[1,2],[3,4]])
dp1=np.array([[5,6],[7,8]])
dp,dp1

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [44]:
c=np.dot(dp,dp1)
c

array([[19, 22],
       [43, 50]])

In [46]:
a=np.array([[11,12],[13,14]])
b=np.array([[15,16],[17,18]])
dot_product=np.dot(a,b)
dot_product

array([[369, 392],
       [433, 460]])

In [48]:
s=np.array([90,10,20,30,40,50,60,70,80,100])
np.percentile(s,70)

np.float64(73.0)

In [51]:
a=np.random.randint(1,100,15)
b=np.random.randint(1,100,24).reshape(6,4)
a,b

(array([15, 10, 83, 30, 48, 11, 25, 54, 62, 75, 98, 35, 41, 21, 95],
       dtype=int32),
 array([[53, 27, 56, 44],
        [78, 76, 44, 54],
        [69, 34, 88, 23],
        [60, 55, 70, 44],
        [44, 78, 62, 72],
        [59, 70, 46, 85]], dtype=int32))

In [52]:
np.sort(a)

array([10, 11, 15, 21, 25, 30, 35, 41, 48, 54, 62, 75, 83, 95, 98],
      dtype=int32)

In [53]:
np.sort(b)

array([[27, 44, 53, 56],
       [44, 54, 76, 78],
       [23, 34, 69, 88],
       [44, 55, 60, 70],
       [44, 62, 72, 78],
       [46, 59, 70, 85]], dtype=int32)

In [54]:
fl=np.random.randint(1,100,15)
fl

array([65, 67, 16, 38, 97, 24, 82, 89, 39, 71, 63,  4, 28, 63, 56],
      dtype=int32)

In [55]:
np.flip(fl)

array([56, 63, 28,  4, 63, 71, 39, 89, 82, 24, 97, 38, 16, 67, 65],
      dtype=int32)

In [57]:
fl1=np.random.randint(1,100,24).reshape(6,4)
fl1

array([[ 5, 51, 31, 62],
       [66, 51, 78,  5],
       [ 7, 32, 13, 57],
       [49, 21, 49, 90],
       [84, 78, 25, 95],
       [70, 94, 22, 79]], dtype=int32)

In [58]:
np.flip(fl1,axis=0)

array([[70, 94, 22, 79],
       [84, 78, 25, 95],
       [49, 21, 49, 90],
       [ 7, 32, 13, 57],
       [66, 51, 78,  5],
       [ 5, 51, 31, 62]], dtype=int32)

In [59]:
de=np.random.randint(1,100,15)
de

array([41, 25, 91, 33,  9, 15, 60, 76, 28, 78, 57, 18, 96, 48, 38],
      dtype=int32)

In [61]:
np.delete(de,0)

array([25, 91, 33,  9, 15, 60, 76, 28, 78, 57, 18, 96, 48, 38],
      dtype=int32)

In [62]:
np.delete(de,[0,2,5])

array([25, 33,  9, 60, 76, 28, 78, 57, 18, 96, 48, 38], dtype=int32)

In [63]:
de

array([41, 25, 91, 33,  9, 15, 60, 76, 28, 78, 57, 18, 96, 48, 38],
      dtype=int32)

In [64]:
np.delete(de,[0,4])

array([25, 91, 33, 15, 60, 76, 28, 78, 57, 18, 96, 48, 38], dtype=int32)

In [65]:
am=np.arange(12).reshape(3,4)
am

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
np.transpose(am)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [70]:
am.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [73]:
arr=np.array([[1,2,3],[4,5,6]])
transpoded_arr=np.transpose(arr)
arr,transpoded_arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [74]:
ra=np.arange(12).reshape(3,4)
ra

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
ra.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
ra1=np.arange(0,8).reshape(2,2,2)
ra1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
np.ravel(ra1)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [78]:
arr=np.array([[1,2,3],[4,5,6]])
flattened_arr=arr.flatten()
flattened_arr

array([1, 2, 3, 4, 5, 6])

In [80]:
ra1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [82]:
import numpy as np
matrix =np.array([[4,7],[2,6]])
inverse_matrix=np.linalg.inv(matrix)
print("orginal matrix:")
print(matrix)
print("\n inverse matrix:")
print(inverse_matrix)

orginal matrix:
[[4 7]
 [2 6]]

 inverse matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [83]:
w1=np.arange(12).reshape(3,4)
w2=np.arange(12,24).reshape(3,4)
w1,w2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [86]:
np.hstack((w1,w2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [87]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [88]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
np.hsplit(w1,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [92]:
arr1=np.array([1,2,3,4,5,6])
splitting=np.split(arr1,3)
splitting

[array([1, 2]), array([3, 4]), array([5, 6])]

In [96]:
np.vsplit(w1,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [3]:
import numpy as np

In [5]:
arr=np.array([10,20,30,40,50])
bool_idx=arr>25
print(bool_idx)
selected_element=arr[bool_idx]
indices=np.array([0,2,4])
fancy_selected=arr[indices]
selected_element,indices

[False False  True  True  True]


(array([30, 40, 50]), array([0, 2, 4]))

In [6]:
g=np.random.randint(1,100,24).reshape(6,4)
g

array([[12, 58, 81, 23],
       [70, 29, 86, 62],
       [44, 63, 15, 70],
       [40, 75, 80, 39],
       [59, 21, 22, 14],
       [81, 83, 33, 73]], dtype=int32)

In [7]:
g>25

array([[False,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False],
       [ True,  True,  True,  True]])

In [8]:
g[g>25]

array([58, 81, 70, 29, 86, 62, 44, 63, 70, 40, 75, 80, 39, 59, 81, 83, 33,
       73], dtype=int32)

In [9]:
g % 2==0

array([[ True,  True, False, False],
       [ True, False,  True,  True],
       [ True, False, False,  True],
       [ True, False,  True, False],
       [False, False,  True,  True],
       [False, False, False, False]])

In [10]:
g[g%2==0]

array([12, 58, 70, 86, 62, 44, 70, 40, 80, 22, 14], dtype=int32)

In [14]:
g[(g>50)&(g%2==0)]

array([58, 70, 86, 62, 70, 80], dtype=int32)

In [16]:
g[~(g>50)&(g%2==0)]

array([12, 44, 40, 22, 14], dtype=int32)

In [17]:
g[np.array([0,2,4])]

array([[12, 58, 81, 23],
       [44, 63, 15, 70],
       [59, 21, 22, 14]], dtype=int32)

In [20]:
scalar=5
array=np.array([1,2,3,4,5])
result_scalar=scalar*array
result_scalar

array([ 5, 10, 15, 20, 25])

In [24]:
arri=np.array([[1,2,3],[4,5,6]])
arrj=np.array([10,20,30])
result_broadcasting=arri*arrj
arri.shape,arrj.shape,result_broadcasting

((2, 3),
 (3,),
 array([[ 10,  40,  90],
        [ 40, 100, 180]]))

In [27]:
arr=np.array([[1,2,3],[4,5,6]])
np.save('my_array.npy',arr)

In [28]:
loaded_arr=np.load('my_array.npy')
loaded_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
loaded_arr[loaded_arr % 2==0]

array([2, 4, 6])

In [3]:
def create_file(file_path,content):
    with open(file_path,'w')as file:
        file.write(content)
        
        
create_file("test.txt", "This is the text file\n this isnew file")

In [4]:
with open("test.txt",'r')as f:
    content=f.read()
    print(content)
    

This is the text file
 this isnew file


In [6]:
with open(r"C:\Users\adity\Documents\Python Script\file handle\test.txt",'w')as f:
    f.write("this is text file")
    f.close()

In [10]:
with open('test.txt','r+')as file:
    content=file.read()
    print('content before writting',content)
    file.seek(0)
    file.write('this is new content')
    file.seek(0)
    update_content=file.read()
    print('content after wriiting',update_content)

content before writting this is new content
content after wriiting this is new content


In [11]:
with open('test.txt','w+')as file:
    file.write('this is new line of text')
    file.seek(0)
    content=file.read()
    print('content after writting',content)
    


content after writting this is new line of text


In [12]:
with open(r"C:\Users\adity\Documents\Python Script\file handle\test.txt",'a')as f:
    f.write("\n this is another line")
    f.write("\n this is nxt line ")
    f.close()

In [13]:
with open(r"C:\Users\adity\Documents\Python Script\file handle\test.txt",'a+')as f:
    f.write("\n this is other line")
    f.seek(0)
    print(f.read())
    f.close()

this is new line of text
 this is another line
 this is nxt line 
 this is other line


In [15]:
mixed_string=["test@gmail.com","123-456-789","start this string","this is string with end ","123456789","contains whitespaces","prestest and posttest",
              "!@#$%^&","string does not satrt with a digits","nowhitespaceshere"]
def create_file(file_path,content):
    with open(file_path,'w')as file:
        for line in content:
            file.write(line+'\n')
file_path='myfile.txt'
create_file(file_path,mixed_string)

In [16]:
with open("myfile.txt","r")as file:
    print(file.read())
    file.close()

test@gmail.com
123-456-789
start this string
this is string with end 
123456789
contains whitespaces
prestest and posttest
!@#$%^&
string does not satrt with a digits
nowhitespaceshere



In [23]:
file=open("myfile.txt",'r')
content=file.readlines()
print(content)
file.close()

['test@gmail.com\n', '123-456-789\n', 'start this string\n', 'this is string with end \n', '123456789\n', 'contains whitespaces\n', 'prestest and posttest\n', '!@#$%^&\n', 'string does not satrt with a digits\n', 'nowhitespaceshere\n']


In [24]:
file=open("myfile.txt",'r')
str=file.readlines()
print(str)
file.close()

['test@gmail.com\n', '123-456-789\n', 'start this string\n', 'this is string with end \n', '123456789\n', 'contains whitespaces\n', 'prestest and posttest\n', '!@#$%^&\n', 'string does not satrt with a digits\n', 'nowhitespaceshere\n']


In [25]:
f=open("myfile.txt",'r')
str=f.read().splitlines()
print(str)
f.close()

['test@gmail.com', '123-456-789', 'start this string', 'this is string with end ', '123456789', 'contains whitespaces', 'prestest and posttest', '!@#$%^&', 'string does not satrt with a digits', 'nowhitespaceshere']


In [26]:
with open("myfile.txt","r")as file:
    data=file.readlines()
    for line in data:
        word=line.split()
        print(word)

['test@gmail.com']
['123-456-789']
['start', 'this', 'string']
['this', 'is', 'string', 'with', 'end']
['123456789']
['contains', 'whitespaces']
['prestest', 'and', 'posttest']
['!@#$%^&']
['string', 'does', 'not', 'satrt', 'with', 'a', 'digits']
['nowhitespaceshere']


In [12]:
f=open("myfile.txt","w")
str='Current content of the file:I am a leaning apython ,python is easy to learn'
f.write(str)
f.close()

In [13]:
f=open("myfile.txt","r")
f.read()

'Current content of the file:I am a leaning apython ,python is easy to learn'

In [14]:
with open("myfile.txt","w") as file:
    l1="Welcome to TurTorialpoint\n"
    l2="write multiple lines\n"
    l3="Done successfull\n"
    l4="Thank you\n"
    file.writelines([l1,l2,l3,l4])
    file.close()

In [16]:
with open("myfile.txt","r") as file:
    print(file.read())

Welcome to TurTorialpoint
write multiple lines
Done successfull
Thank you



In [17]:
with open("myfile.txt","r") as file:
        print(file.readlines())

['Welcome to TurTorialpoint\n', 'write multiple lines\n', 'Done successfull\n', 'Thank you\n']


In [18]:
with open("myfile.txt","r") as f:
    data=f.read().strip().split('\n')
    print(data)
    f.close()

['Welcome to TurTorialpoint', 'write multiple lines', 'Done successfull', 'Thank you']


In [20]:
with open("myfile.txt","r") as f:
    data=f.read().split('\n')
    print(data)

['Welcome to TurTorialpoint', 'write multiple lines', 'Done successfull', 'Thank you', '']


In [24]:
fvar=open("myfile.txt","w")
list1=["Hello\n","Hi\n","How ru"]
fvar.writelines(list1)
fvar.close()

In [27]:
with open("myfile.txt","r")as f:
    data=f.read().split('\n')
    print(data)

['Hello', 'Hi', 'How ru']


In [28]:
f=open("myfile.txt","a")
str_to_write='/nGood Night'
f.write(str_to_write)
f.close()

In [30]:
f=open("myfile.txt","r")
f.read().strip().split('\n')

['Hello', 'Hi', 'How ru/nGood Night']

In [32]:
f=open("myfile.txt","a+")
str=input("Enter Text")
f.write(str+"\n")
f.seek(0)
str=f.read().strip()
print(str)
f.close()


Hello
Hi
How ru/nGood Nightsathya
python


In [33]:
import warnings
warnings.filterwarnings('ignore')
with open("myfile.txt","r")as f:
    with open("myfile.txt","w") as f1:
        for line in f:
            f1.write(line)

In [13]:
import os
if os.path.exists("myfile.txt"):
    print("file")
else:
    print("The file does not exist")

file


In [14]:
if os.path.exists("output.txt"):
    print("file")
else:
    print("The file does not exist")

The file does not exist


In [31]:
def create_file(file_path,content):
    with open(file_path,'w')as file:
        file.write(content)
    print(f"file'{file_path}'created successfully")
create_file('data.csv','Name,Age,City\njohn,30,blr\nvishal,40,bombai')

file'data.csv'created successfully


In [32]:
import csv
with open("data.csv",'r')as file:
    reader=csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age', 'City']
['john', '30', 'blr']
['vishal', '40', 'bombai']


In [33]:
with open("data.csv",'w',newline='')as file:
    writer=csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["Aline","30","kerala"])
    writer.writerow(["Bob","55","delhi"])


In [34]:
import csv
with open("data.csv","w",newline='')as file:
    writer=csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerows([["Aline","30","kerala"],["Bob","55","delhi"],["Raja","52","Blr"]])

In [35]:
with open("data.csv","a",newline='')as file:
    writer=csv.writer(file)
    writer.writerow(["xyz","36","mys"])

In [36]:
with open("data.csv","r",newline='')as file:
    reader=csv.reader(file)
    data=list(reader)
    print(data)

[['Name', 'Age', 'City'], ['Aline', '30', 'kerala'], ['Bob', '55', 'delhi'], ['Raja', '52', 'Blr'], ['xyz', '36', 'mys']]


In [37]:
with open("data.csv","r")as file:
    reader=csv.DictReader(file)
    for row in reader:
        print(row["Name"],row["Age"],row["City"])

Aline 30 kerala
Bob 55 delhi
Raja 52 Blr
xyz 36 mys


In [38]:
with open("data.csv","r",newline='')as file:
    reader=csv.reader(file)
    header=next(reader)
    age_column=[row[2] for row in reader]
    print(age_column)

['kerala', 'delhi', 'Blr', 'mys']


In [39]:
def create_file(file_path,content):
    with open(file_path,'w')as f:
        f.write(content)
    print(f"file'{file_path}'created successfully")
    
create_file('data.json','{"name":"john","age":"30","city":"blr"}')


file'data.json'created successfully


In [40]:
import json
with open("data.json","r")as f:
    data=json.load(f)
    print(data)

{'name': 'john', 'age': '30', 'city': 'blr'}


In [42]:
data=[
    {"name":"aline","age":"25","city":"mys"},
    {"name":"bob","age":"28","city":"blr"},
    {"name":"charlie","age":"35","city":"bombai"},
    {"name":{"first_name":"777","last_name":"charli"},"age":"25","city":"goa"}
]
with open("data.json","w")as f:
    json.dump(data,f)
    

In [43]:
with open("data.json","r")as f:
    data=f.read()
    print(data)

[{"name": "aline", "age": "25", "city": "mys"}, {"name": "bob", "age": "28", "city": "blr"}, {"name": "charlie", "age": "35", "city": "bombai"}, {"name": {"first_name": "777", "last_name": "charli"}, "age": "25", "city": "goa"}]


In [44]:
with open("data.json","r")as f:
    data=json.load(f)
city_of_first_person=data[3]["name"]['first_name']
print(city_of_first_person)

777


In [45]:
new_entry=[{"name":"python","age":"45","city":"goa"}]
data.append(new_entry)

with open("data.json","w")as f:
    json.dump(data,f)

In [46]:
with open("data.json","r")as f:
    data=json.load(f)
    for item in data:
        print(item)

{'name': 'aline', 'age': '25', 'city': 'mys'}
{'name': 'bob', 'age': '28', 'city': 'blr'}
{'name': 'charlie', 'age': '35', 'city': 'bombai'}
{'name': {'first_name': '777', 'last_name': 'charli'}, 'age': '25', 'city': 'goa'}
[{'name': 'python', 'age': '45', 'city': 'goa'}]


In [49]:
def read():
    file_path=r'C:\Users\adity\Documents\Python Script\file handle\myfile.txt'
    
    try:
        with open(file_path,'r')as f:
            lines=f.readlines()
            if not lines:
                print("The file is empty")
            else:
                print("file content")
                for line in lines:
                    print(line.strip())
    except FileNotFoundError:
        print(f"filr not found at path:{file_path}")
    except Exception as e:
        print(f"an error occurred:{e}")
read()

The file is empty
