In [6]:
import numpy as np

In [10]:
a=np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 9])

In [11]:
np.size(a)

11

In [12]:
diagonal_matrix = np.diag([2, 4, 6])
print(diagonal_matrix)

[[2 0 0]
 [0 4 0]
 [0 0 6]]


In [15]:
arr=np.arange(12)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
arr[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
ma=np.array([8, 3, 7, 1, 2, 6, 5])
ma=np.max(ma)
print(ma)

8


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 6])
print("Original array:", arr)

indices = np.array([0, 2, 3])
fancy_selected = arr[indices]

print("Selected elements using fancy indexing:", fancy_selected)

Original array: [1 2 3 6]
Selected elements using fancy indexing: [1 3 6]


In [17]:
matrix = np.ones((5, 5), dtype='int')
matrix[1:-1, 1:-1]=0
print(matrix)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
multiplication = a * b
multiplication

array([ 4, 10, 18])

In [20]:
array = np.array([1, 4, 2, 7, 5, 0])
count = np.sum(array > 3)
print("Number of elements greater than 3:", count)

Number of elements greater than 3: 3


In [24]:

arr2 = np.array([1, 2, 3, 4])
matrix = arr2.reshape(2, 2)
matrix


array([[1, 2],
       [3, 4]])

In [27]:
arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_means = np.mean(arr3, axis=1)
print("Mean along each row:", row_means)

Mean along each row: [2. 5. 8.]


In [32]:
arr4 = np.array([10, 15, 20, 25, 30])
arr4[arr4 % 2 != 0] = -1
print("Array after replacing odd numbers with -1:", arr4)

Array after replacing odd numbers with -1: [10 -1 20 -1 30]
